// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfczyojeumffzzzjlyqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmY3p5b2pldW1mZnp6empseXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDQ3NzIsImV4cCI6MjA2ODU4MDc3Mn0.CawjLrSaxjZKWM4ktiUwPIsdjNjKixMxgd9_Ah2_B8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});